/**
 * Implements the abstract coreClass that implements common methods for higher-end classes like Event Service
 * and Logging Service
 */
import * as fetch from 'node-fetch'
import { Credentials } from './credentials'
import { ApplicationFrameworkError, PanCloudError } from './error'
import { commonLogger, logLevel, retrier } from './common';

export interface coreStats {
    apiTransactions: number
}

/**
 * Interface to provide configuration options to the core class
 */
export interface coreOptions {
    /**
     * credential object that should be used in the coreClass instance
     */
    credential: Credentials,
    /**
     * Master API entry point to be used by the coreClass instance
     */
    entryPoint: string,
    /**
     * Toggle the access_token auto-refresh feature
     */
    autoRefresh?: boolean,
    /**
     * Minimum level of logs that should be generated by the coreClass
     */
    level?: logLevel
    /**
     * Number of times a fetch operation must be retried in case of exception
     */
    retrierCount?: number
    /**
     * Delay (in milliseconds) between retry attempts
     */
    retrierDelay?: number
}

/**
 * This class should not be used directly. It is meant to be extended. Use higher-level classes like LoggingService
 * or EventService
 */
export class coreClass {
    /**
     * Credential object to be used by this instance
     */
    protected cred: Credentials
    /**
     * Master Application Framework API entry point
     */
    protected entryPoint: string
    /**
     * Keeps the HTTP headers used by the user agent. mainly used to keep the Authorization header (bearer access token)
     */
    protected fetchHeaders: { [i: string]: string }
    private autoR: boolean
    private retrierCount?: number
    private retrierDelay?: number
    lastResponse: any
    public className: string
    protected stats: coreStats

    /**
     * 
     * @param ops configuration options for this instance
     */
    protected constructor(ops: coreOptions) {
        this.className = "coreClass"
        this.cred = ops.credential
        this.entryPoint = ops.entryPoint
        if (ops.level != undefined && ops.level != logLevel.INFO) {
            commonLogger.level = ops.level
        }
        if (ops.autoRefresh == undefined) {
            this.autoR = true
        } else {
            this.autoR = ops.autoRefresh
        }
        this.retrierCount = ops.retrierCount
        this.retrierDelay = ops.retrierDelay
        this.stats = {
            apiTransactions: 0
        }
        this.setFetchHeaders()
    }


    /**
     * Prepares the HTTP headers. Mainly used to keep the Autorization header (bearer access-token)
     */
    private setFetchHeaders(): void {
        this.fetchHeaders = {
            'Authorization': 'Bearer ' + this.cred.get_access_token(),
            'Content-Type': 'application/json'
        }
        commonLogger.info(this, 'updated authorization header')
    }

    /**
     * Triggers the credential object access-token refresh procedure and updates the HTTP headers
     */
    protected async refresh(): Promise<void> {
        await this.cred.refresh_access_token()
        this.setFetchHeaders()
    }

    private async checkAutoRefresh(): Promise<void> {
        if (this.autoR) {
            if (await this.cred.autoRefresh()) {
                this.setFetchHeaders()
            }
        }
    }

    private async fetchXWrap(url: string, method: string, body?: string, timeout?: number): Promise<any> {
        this.stats.apiTransactions++
        await this.checkAutoRefresh()
        let rinit: fetch.RequestInit = {
            headers: this.fetchHeaders,
            method: method
        }
        if (timeout) {
            rinit.timeout = timeout
        }
        if (body) {
            rinit.body = body
        }
        commonLogger.debug(this, `fetch operation to ${url}`, method, body)
        let r = await retrier(this, this.retrierCount, this.retrierDelay, fetch.default, url, rinit)
        let r_text = await r.text()
        if (r_text.length == 0) {
            commonLogger.info(this, 'fetch response is null')
            return null
        }
        let r_json: any
        try {
            r_json = JSON.parse(r_text)
        } catch (exception) {
            throw new PanCloudError(this, 'PARSER', `Invalid JSON: ${exception.message}`)
        }
        if (!r.ok) {
            commonLogger.alert(this, r_text, "FETCHXWRAP")
            throw new ApplicationFrameworkError(this, r_json)
        }
        commonLogger.debug(this, 'fetch response', undefined, r_json)
        return r_json
    }

    /**
     * Convenience method that abstracts a GET operation to the Application Framework. Captures both non JSON responses
     * as well as Application Framework errors (non-200) throwing exceptions in both cases.
     * @param url URL to be called
     * @param timeout milliseconds before issuing a timeout exeception. The operation is wrapped by a 'retrier'
     * that will retry the operation. User can change default retry parameters (3 times / 100 ms) using the right
     * class configuration properties
     * @returns the object returned by the Application Framework
     */
    protected async fetchGetWrap(url: string, timeout?: number): Promise<any> {
        return await this.fetchXWrap(url, "GET", undefined, timeout)
    }

    /**
     * Convenience method that abstracts a POST operation to the Application Framework
     */
    protected async fetchPostWrap(url: string, body?: string, timeout?: number): Promise<any> {
        return await this.fetchXWrap(url, "POST", body, timeout)
    }

    /**
     * Convenience method that abstracts a PUT operation to the Application Framework
     */
    protected async fetchPutWrap(url: string, body?: string, timeout?: number): Promise<any> {
        return await this.fetchXWrap(url, "PUT", body, timeout)
    }

    /**
     * Convenience method that abstracts a DELETE operation to the Application Framework
     */
    protected async fetchDeleteWrap(url: string, timeout?: number): Promise<any> {
        return await this.fetchXWrap(url, "DELETE", undefined, timeout)
    }

    /**
     * Convenience method that abstracts a DELETE operation to the Application Framework
     */
    protected async void_X_Operation(url: string, payload?: string, method = "POST"): Promise<void> {
        let r_json = await this.fetchXWrap(url, method, payload);
        this.lastResponse = r_json
    }
}